server:
  port: 8081
spring:
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant_path_matcher
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 5000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/android_bs?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
logging:
  level:
    root: info
